/**
 * Ansible catalog actions
 */

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_PORTFOLIOS = 'FETCH_PORTFOLIOS';
export const FETCH_PLATFORMS = 'FETCH_PLATFORMS';
export const FETCH_PORTFOLIO_ITEMS = 'FETCH_PORTFOLIO_ITEMS';
export const SET_CATALOG_LOADING_STATE = 'SET_LOADING_STATE';

/**
 * Automation hub actions
 */
export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const FETCH_PARTNERS = 'FETCH_PARTNERS';
export const FETCH_SYNC_COLLECTIONS = 'FETCH_SYNC_COLLECTIONS';
export const SET_HUB_LOADING_STATE = 'SET_LOADING_STATE';

/**
 * Tower analytics actions
 */
export const FETCH_CLUSTERS = 'FETCH_CLUSTERS';
export const FETCH_ERROR_NOTIFICATIONS = 'FETCH_ERROR_NOTIFICATIONS';
export const FETCH_WARNING_NOTIFICATIONS = 'FETCH_WARNING_NOTIFICATIONS';
export const FETCH_JOBS = 'FETCH_JOBS';
export const SET_ANALYTICS_LOADING_STATE = 'SET_LOADING_STATE';

/**
 * In18l actions
 */

export const INITIALIZE_I18N = '@@i18l/INITIALIZE_I18N';
